import { createClient } from '@/lib/supabase/server';
import { tryHashIp } from './ipHash';

// Database types are regenerated by `npm run db:types` after migration push.
// Until then, cast through a minimal-shape interface to keep this file type-safe
// without touching the strict global Database type.
type AuditRpcArgs = {
  p_action: string;
  p_severity: string;
  p_entity: string | null;
  p_entity_id: string | null;
  p_summary: string | null;
  p_details: Record<string, unknown> | null;
  p_ip_hash: string | null;
  p_user_agent: string | null;
  p_request_id: string | null;
};
type DlqRow = { payload: unknown; error_msg: string };
type MinimalSupabase = {
  rpc: (fn: string, args: AuditRpcArgs) => Promise<{ data: unknown; error: Error | null }>;
  from: (table: string) => { insert: (row: DlqRow) => Promise<{ error: Error | null }> };
};

/**
 * Discriminated union of every audit event the system can emit.
 * Adding a new event = add a variant here so TypeScript enforces correct shape.
 */
export type AuditEvent =
  // ===== Auth & security =====
  | { action: 'auth.login_success'; severity: 'info'; details: { method: 'password' | 'magic_link' | 'oauth' } }
  | { action: 'auth.login_fail'; severity: 'warn'; details: { reason: 'wrong_password' | 'cross_realm' | 'rate_limited' | 'mfa_failed' } }
  | { action: 'auth.rate_limited'; severity: 'warn'; details: { tier: number; key: string } }
  | { action: 'auth.idle_logout'; severity: 'info'; details?: { idleSeconds?: number } }
  | { action: 'auth.logout'; severity: 'info' }
  | { action: 'auth.cross_realm_blocked'; severity: 'warn'; details: { realm: 'storefront' | 'admin' } }
  | { action: 'auth.mfa_enrolled'; severity: 'info' }
  | { action: 'auth.mfa_failed'; severity: 'warn' }
  | { action: 'auth.mfa_success'; severity: 'info' }
  | { action: 'auth.backup_code_used'; severity: 'warn' }
  | { action: 'auth.captcha_challenged'; severity: 'info'; details: { reason: string } }
  | { action: 'auth.magic_link_sent'; severity: 'warn'; details: { email_hash: string } }
  | { action: 'auth.session_revoked'; severity: 'warn'; details: { reason: string } }
  | { action: 'auth.password_changed'; severity: 'info' }
  | { action: 'auth.password_change_failed'; severity: 'warn'; details: { reason: string } }
  | { action: 'auth.mfa_unenrolled'; severity: 'warn' }
  | { action: 'auth.mfa_unenroll_failed'; severity: 'warn'; details: { reason: string } }
  // ===== Data mutations =====
  | { action: 'product.created' | 'product.updated' | 'product.archived' | 'product.restored' | 'product.price_changed' | 'product.stock_changed';
      severity: 'info'; entity: 'product'; entity_id: string; summary: string; details?: Record<string, unknown> }
  | { action: 'category.created' | 'category.updated' | 'category.deleted';
      severity: 'info'; entity: 'category'; entity_id: string; summary?: string; details?: Record<string, unknown> }
  | { action: 'order.status_changed' | 'order.refunded' | 'order.cancelled' | 'order.shipped' | 'order.note_added';
      severity: 'info' | 'warn'; entity: 'order'; entity_id: string; details?: Record<string, unknown> }
  | { action: 'voucher.created' | 'voucher.updated' | 'voucher.disabled' | 'voucher.used';
      severity: 'info'; entity: 'voucher'; entity_id: string; details?: Record<string, unknown> }
  | { action: 'banner.created' | 'banner.updated' | 'banner.activated' | 'banner.deactivated';
      severity: 'info'; entity: 'banner'; entity_id: string }
  | { action: 'customer.banned' | 'customer.unbanned' | 'customer.note_added' | 'customer.address_edited_by_staff';
      severity: 'warn'; entity: 'customer'; entity_id: string; details?: Record<string, unknown> }
  | { action: 'rbac.role_assigned' | 'rbac.role_revoked' | 'rbac.permission_changed' | 'rbac.staff_invited' | 'rbac.staff_disabled';
      severity: 'warn'; entity: 'staff'; entity_id: string; details?: Record<string, unknown> }
  | { action: 'setting.updated'; severity: 'info'; entity: 'setting'; details: { key: string; old?: unknown; new: unknown } }
  | { action: 'gdpr.user_anonymized'; severity: 'critical'; entity: 'user'; entity_id: string };

export type AuditContext = {
  ip?: string | null;
  userAgent?: string | null;
  requestId?: string | null;
};

/**
 * Build an AuditContext from the current request headers.
 * Shared helper — use instead of copy-pasting auditCtx() in every action file.
 */
export async function getAuditContext(): Promise<AuditContext> {
  // Dynamic import to avoid circular deps in edge middleware
  const { headers } = await import('next/headers');
  const h = await headers();
  return {
    ip: h.get('x-forwarded-for')?.split(',')[0]?.trim() ?? null,
    userAgent: h.get('user-agent'),
  };
}

let failureCounter = 0;

/**
 * Best-effort audit log writer. Never throws into the calling business logic.
 * On failure: console.error → Sentry (if configured) → audit_logs_dlq table.
 *
 * Trade-off: ~5ms blocking insert. Async-ification is phase 2.
 */
export async function audit(event: AuditEvent, ctx?: AuditContext): Promise<void> {
  try {
    const supabase = (await createClient()) as unknown as MinimalSupabase;
    const ipHash = ctx?.ip ? tryHashIp(ctx.ip) : null;

    const entity = 'entity' in event ? event.entity : null;
    const entity_id = 'entity_id' in event ? event.entity_id : null;
    const summary = 'summary' in event ? event.summary ?? null : null;
    const details = 'details' in event ? event.details ?? null : null;

    const { error } = await supabase.rpc('log_admin_action_v2', {
      p_action: event.action,
      p_severity: event.severity,
      p_entity: entity,
      p_entity_id: entity_id,
      p_summary: summary,
      p_details: details,
      p_ip_hash: ipHash,
      p_user_agent: ctx?.userAgent ?? null,
      p_request_id: ctx?.requestId ?? null,
    });
    if (error) throw error;
    failureCounter = 0;
  } catch (err) {
    failureCounter++;
    // 1. Always console
    console.error('[AUDIT_FAILURE]', { action: event.action, err });

    // 2. Sentry (best effort)
    try {
      const Sentry = await import('@sentry/nextjs').catch(() => null);
      if (Sentry?.captureException) {
        Sentry.captureException(err, {
          level: 'error',
          tags: { component: 'audit_log', action: event.action },
          extra: { event, ctx },
        });
        if (failureCounter > 10 && Sentry.captureMessage) {
          Sentry.captureMessage('Audit log failing repeatedly — investigate DB', 'fatal');
        }
      }
    } catch {
      /* sentry not configured — fine */
    }

    // 3. Dead-letter table for replay
    try {
      const supabase = (await createClient()) as unknown as MinimalSupabase;
      await supabase.from('audit_logs_dlq').insert({
        payload: { event, ctx },
        error_msg: err instanceof Error ? err.message : String(err),
      });
    } catch {
      /* even DLQ failed — only console.error remains */
    }
  }
}
